--- !<MAP>
contentType: "MAP"
firstIndex: "2018-10-15 03:26"
lastIndex: "2018-10-15 03:26"
game: "Unreal Tournament"
name: "DM-PrometheusFinal"
author: "Chris Sheridan"
description: "None"
releaseDate: "2006-12"
attachments:
- type: "IMAGE"
  name: "DM-PrometheusFinal_shot_1.png"
  url: "https://f002.backblazeb2.com/Unreal Tournament/Maps/DeathMatch/P/DM-PrometheusFinal_shot_1.png"
originalFilename: "dm-prometheusfinal.zip"
hash: "4807767f827231244ddbb7bd3c5e7e67e89d038b"
fileSize: 277616
files:
- name: "DM-PrometheusFinal.unr"
  fileSize: 1058106
  hash: "7c7d6a538301e64bef7d7e82e136defa45a16337"
otherFiles: 1
downloads:
- url: "https://f002.backblazeb2.com/Unreal Tournament/Maps/DeathMatch/P/dm-prometheusfinal.zip"
  main: true
  added: "2018-10-15"
  lastChecked: "2018-10-15"
  ok: true
  repack: false
  deleted: false
deleted: false
gametype: "DeathMatch"
title: "PrometheusFinal"
playerCount: "2-12"
